package com.example.jadp.model;

public enum PiiType {
    RESIDENT_REGISTRATION_NUMBER,
    DRIVER_LICENSE_NUMBER,
    PASSPORT_NUMBER,
    FOREIGNER_REGISTRATION_NUMBER,
    MOBILE_PHONE_NUMBER,
    LANDLINE_PHONE_NUMBER,
    CREDIT_CARD_NUMBER,
    BANK_ACCOUNT_NUMBER,
    PERSON_NAME,
    EMAIL_ADDRESS,
    IP_ADDRESS,
    STREET_ADDRESS
}
